/**
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveConvertApiClient);
  }
}(this, function(expect, CloudmersiveConvertApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveConvertApiClient.DocxStyle();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DocxStyle', function() {
    it('should create an instance of DocxStyle', function() {
      // uncomment below and update the code to test DocxStyle
      //var instance = new CloudmersiveConvertApiClient.DocxStyle();
      //expect(instance).to.be.a(CloudmersiveConvertApiClient.DocxStyle);
    });

    it('should have the property styleID (base name: "StyleID")', function() {
      // uncomment below and update the code to test the property styleID
      //var instance = new CloudmersiveConvertApiClient.DocxStyle();
      //expect(instance).to.be();
    });

    it('should have the property path (base name: "Path")', function() {
      // uncomment below and update the code to test the property path
      //var instance = new CloudmersiveConvertApiClient.DocxStyle();
      //expect(instance).to.be();
    });

    it('should have the property bold (base name: "Bold")', function() {
      // uncomment below and update the code to test the property bold
      //var instance = new CloudmersiveConvertApiClient.DocxStyle();
      //expect(instance).to.be();
    });

    it('should have the property italic (base name: "Italic")', function() {
      // uncomment below and update the code to test the property italic
      //var instance = new CloudmersiveConvertApiClient.DocxStyle();
      //expect(instance).to.be();
    });

    it('should have the property underline (base name: "Underline")', function() {
      // uncomment below and update the code to test the property underline
      //var instance = new CloudmersiveConvertApiClient.DocxStyle();
      //expect(instance).to.be();
    });

    it('should have the property fontSize (base name: "FontSize")', function() {
      // uncomment below and update the code to test the property fontSize
      //var instance = new CloudmersiveConvertApiClient.DocxStyle();
      //expect(instance).to.be();
    });

    it('should have the property fontFamily (base name: "FontFamily")', function() {
      // uncomment below and update the code to test the property fontFamily
      //var instance = new CloudmersiveConvertApiClient.DocxStyle();
      //expect(instance).to.be();
    });

  });

}));
