/**
 * convertapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Convertapi);
  }
}(this, function(expect, Convertapi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Convertapi.HtmlToPdfRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('HtmlToPdfRequest', function() {
    it('should create an instance of HtmlToPdfRequest', function() {
      // uncomment below and update the code to test HtmlToPdfRequest
      //var instane = new Convertapi.HtmlToPdfRequest();
      //expect(instance).to.be.a(Convertapi.HtmlToPdfRequest);
    });

    it('should have the property html (base name: "Html")', function() {
      // uncomment below and update the code to test the property html
      //var instane = new Convertapi.HtmlToPdfRequest();
      //expect(instance).to.be();
    });

    it('should have the property extraLoadingWait (base name: "ExtraLoadingWait")', function() {
      // uncomment below and update the code to test the property extraLoadingWait
      //var instane = new Convertapi.HtmlToPdfRequest();
      //expect(instance).to.be();
    });

  });

}));
