/**
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveConvertApiClient);
  }
}(this, function(expect, CloudmersiveConvertApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveConvertApiClient.EditTextApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EditTextApi', function() {
    describe('editTextBase64Decode', function() {
      it('should call editTextBase64Decode successfully', function(done) {
        //uncomment below and update the code to test editTextBase64Decode
        //instance.editTextBase64Decode(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editTextBase64Detect', function() {
      it('should call editTextBase64Detect successfully', function(done) {
        //uncomment below and update the code to test editTextBase64Detect
        //instance.editTextBase64Detect(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editTextBase64Encode', function() {
      it('should call editTextBase64Encode successfully', function(done) {
        //uncomment below and update the code to test editTextBase64Encode
        //instance.editTextBase64Encode(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editTextChangeLineEndings', function() {
      it('should call editTextChangeLineEndings successfully', function(done) {
        //uncomment below and update the code to test editTextChangeLineEndings
        //instance.editTextChangeLineEndings(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editTextDetectLineEndings', function() {
      it('should call editTextDetectLineEndings successfully', function(done) {
        //uncomment below and update the code to test editTextDetectLineEndings
        //instance.editTextDetectLineEndings(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editTextFindRegex', function() {
      it('should call editTextFindRegex successfully', function(done) {
        //uncomment below and update the code to test editTextFindRegex
        //instance.editTextFindRegex(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editTextFindSimple', function() {
      it('should call editTextFindSimple successfully', function(done) {
        //uncomment below and update the code to test editTextFindSimple
        //instance.editTextFindSimple(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editTextRemoveAllWhitespace', function() {
      it('should call editTextRemoveAllWhitespace successfully', function(done) {
        //uncomment below and update the code to test editTextRemoveAllWhitespace
        //instance.editTextRemoveAllWhitespace(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editTextRemoveHtml', function() {
      it('should call editTextRemoveHtml successfully', function(done) {
        //uncomment below and update the code to test editTextRemoveHtml
        //instance.editTextRemoveHtml(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editTextReplaceRegex', function() {
      it('should call editTextReplaceRegex successfully', function(done) {
        //uncomment below and update the code to test editTextReplaceRegex
        //instance.editTextReplaceRegex(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editTextReplaceSimple', function() {
      it('should call editTextReplaceSimple successfully', function(done) {
        //uncomment below and update the code to test editTextReplaceSimple
        //instance.editTextReplaceSimple(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editTextTextEncodingDetect', function() {
      it('should call editTextTextEncodingDetect successfully', function(done) {
        //uncomment below and update the code to test editTextTextEncodingDetect
        //instance.editTextTextEncodingDetect(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editTextTrimWhitespace', function() {
      it('should call editTextTrimWhitespace successfully', function(done) {
        //uncomment below and update the code to test editTextTrimWhitespace
        //instance.editTextTrimWhitespace(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
