/**
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveConvertApiClient);
  }
}(this, function(expect, CloudmersiveConvertApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveConvertApiClient.EditHtmlApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EditHtmlApi', function() {
    describe('editHtmlHtmlAppendHeaderTag', function() {
      it('should call editHtmlHtmlAppendHeaderTag successfully', function(done) {
        //uncomment below and update the code to test editHtmlHtmlAppendHeaderTag
        //instance.editHtmlHtmlAppendHeaderTag(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editHtmlHtmlAppendHeading', function() {
      it('should call editHtmlHtmlAppendHeading successfully', function(done) {
        //uncomment below and update the code to test editHtmlHtmlAppendHeading
        //instance.editHtmlHtmlAppendHeading(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editHtmlHtmlAppendImageFromUrl', function() {
      it('should call editHtmlHtmlAppendImageFromUrl successfully', function(done) {
        //uncomment below and update the code to test editHtmlHtmlAppendImageFromUrl
        //instance.editHtmlHtmlAppendImageFromUrl(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editHtmlHtmlAppendImageInline', function() {
      it('should call editHtmlHtmlAppendImageInline successfully', function(done) {
        //uncomment below and update the code to test editHtmlHtmlAppendImageInline
        //instance.editHtmlHtmlAppendImageInline(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editHtmlHtmlAppendParagraph', function() {
      it('should call editHtmlHtmlAppendParagraph successfully', function(done) {
        //uncomment below and update the code to test editHtmlHtmlAppendParagraph
        //instance.editHtmlHtmlAppendParagraph(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editHtmlHtmlCreateBlankDocument', function() {
      it('should call editHtmlHtmlCreateBlankDocument successfully', function(done) {
        //uncomment below and update the code to test editHtmlHtmlCreateBlankDocument
        //instance.editHtmlHtmlCreateBlankDocument(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editHtmlHtmlGetLanguage', function() {
      it('should call editHtmlHtmlGetLanguage successfully', function(done) {
        //uncomment below and update the code to test editHtmlHtmlGetLanguage
        //instance.editHtmlHtmlGetLanguage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editHtmlHtmlGetLinks', function() {
      it('should call editHtmlHtmlGetLinks successfully', function(done) {
        //uncomment below and update the code to test editHtmlHtmlGetLinks
        //instance.editHtmlHtmlGetLinks(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editHtmlHtmlGetRelCanonical', function() {
      it('should call editHtmlHtmlGetRelCanonical successfully', function(done) {
        //uncomment below and update the code to test editHtmlHtmlGetRelCanonical
        //instance.editHtmlHtmlGetRelCanonical(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editHtmlHtmlGetSitemap', function() {
      it('should call editHtmlHtmlGetSitemap successfully', function(done) {
        //uncomment below and update the code to test editHtmlHtmlGetSitemap
        //instance.editHtmlHtmlGetSitemap(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editHtmlHtmlSetLanguage', function() {
      it('should call editHtmlHtmlSetLanguage successfully', function(done) {
        //uncomment below and update the code to test editHtmlHtmlSetLanguage
        //instance.editHtmlHtmlSetLanguage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editHtmlHtmlSetRelCanonical', function() {
      it('should call editHtmlHtmlSetRelCanonical successfully', function(done) {
        //uncomment below and update the code to test editHtmlHtmlSetRelCanonical
        //instance.editHtmlHtmlSetRelCanonical(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editHtmlHtmlSetSitemapUrl', function() {
      it('should call editHtmlHtmlSetSitemapUrl successfully', function(done) {
        //uncomment below and update the code to test editHtmlHtmlSetSitemapUrl
        //instance.editHtmlHtmlSetSitemapUrl(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
